// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MottoMap.Data.AppData;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MottoMap.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251001233531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MottoMap.Models.FilialEntity", b =>
                {
                    b.Property<int>("IdFilial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IdFilial");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFilial"));

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("Cidade");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("Endereco");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("Estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("Nome");

                    b.HasKey("IdFilial");

                    b.ToTable("NET_C3_Filial");
                });

            modelBuilder.Entity("MottoMap.Models.FuncionarioEntity", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IdFuncionario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("Funcao");

                    b.Property<int>("IdFilial")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IdFilial");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("Nome");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdFilial");

                    b.ToTable("NET_C3_Funcionario");
                });

            modelBuilder.Entity("MottoMap.Models.MotosEntity", b =>
                {
                    b.Property<int>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IdMoto");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoto"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Ano");

                    b.Property<string>("Cor")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("Cor");

                    b.Property<int>("IdFilial")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IdFilial");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("Marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("Modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("Placa");

                    b.Property<int?>("Quilometragem")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Quilometragem");

                    b.HasKey("IdMoto");

                    b.HasIndex("IdFilial");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("NET_C3_Motos");
                });

            modelBuilder.Entity("MottoMap.Models.FuncionarioEntity", b =>
                {
                    b.HasOne("MottoMap.Models.FilialEntity", "Filial")
                        .WithMany("Funcionarios")
                        .HasForeignKey("IdFilial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("MottoMap.Models.MotosEntity", b =>
                {
                    b.HasOne("MottoMap.Models.FilialEntity", "Filial")
                        .WithMany("Motos")
                        .HasForeignKey("IdFilial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("MottoMap.Models.FilialEntity", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
